name: Pull Request Action
on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: main@v1
      - name: pull-request
        uses: Govardhan235/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.GGITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "[Example] Simple demo"
